### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by ankushbhardwxj** [anuraghazra/anuraghazra.github.io#17]
https://github.com/anuraghazra/anuraghazra.github.io/blob/ba27b64b740b3aa33fb90678482d5faf34b74ddc/src/components/Layout/Footer.js#L32-L40

@anuraghazra Found a minor but quite visible typo, should be "Made with love by Gatsby & Me". Also, maybe replace "love" by ❤️ .

**Comment by anuraghazra** [comment]
Made by gatsby? :thinking:  i think it should be "with" gatsby. 
if i write "made by gatsby & me" then that would mean gatsby is a person and he helped me build the site.
