### ISSUE TITLE
Typo in home.js

### ISSUE THREAD

**Issue by prdp1137** [anuraghazra/anuraghazra.github.io#2]
Javascript is used as Javascirpt and beautiful as beautifull.

**Comment by prdp1137** [comment]
**Places:**

**Typo of _javascript_:**

https://github.com/anuraghazra/anuraghazra.github.io/blob/3efea93ab057372a874c0ac6aaf8fffac9ec0135/src/components/Home/Home.js#L27

https://github.com/anuraghazra/anuraghazra.github.io/blob/3efea93ab057372a874c0ac6aaf8fffac9ec0135/src/components/Home/Home.js#L29

**Typo of _beautiful_:**

https://github.com/anuraghazra/anuraghazra.github.io/blob/3efea93ab057372a874c0ac6aaf8fffac9ec0135/src/components/Home/Home.js#L37

**Comment by anuraghazra** [comment]
Thank you for reporting.
